dist: xenial

notifications:
  email: false

sudo: required

language: python
python:
  - "3.7"

services:
  - docker

addons:
  sonarcloud:
    token:
      secure: $SONAR_TOKEN$


git:
  quiet: true

before_install:
  - sudo apt-get update
  - sudo apt-get install dos2unix

jobs:
  include:
    - stage: test
      script:
        - cd ./backend
        - nosetests -v --with-xcoverage --cover-package=bin --cover-inclusive --cover-xml bin/test/ --cover-erase
        - mv ./coverage.xml ./bin/test/
    - stage: build
      script:
        - dos2unix ./app_deployer.sh
        - ./app_deployer.sh start
    - stage: sonar
      script:
        - sonar-scanner