dist: xenial

notifications:
  email: false

sudo: required

language: python
python:
  - "3.7"

git:
  quiet: true
  depth: false

services:
  - docker

addons:
  sonarcloud:
    organization: "anjo-hsr"
    token:
      secure: $SONAR_TOKEN

before_install:
  - sudo apt-get update
  - sudo apt-get install dos2unix

jobs:
  include:
    - stage: test
      script:
        - cd ./backend
        - nosetests -v --match="^(?:|[\b_\.\-])[Tt]est" --cover-package=bin --cover-min-percentage=50 --cover-inclusive --cover-erase --with-xcoverage --cover-xml bin/test

    - stage: build
      script:
        - dos2unix ./app_deployer.sh
        - ./app_deployer.sh recreate

    - stage: sonar
      script:
        - cd ./backend
        - nosetests -v --match="^(?:|[\b_\.\-])[Tt]est" --cover-package=bin --cover-min-percentage=50 --cover-inclusive --cover-erase --with-xcoverage --cover-xml bin/test
        - mv ./coverage.xml ./bin/test/
        - cd ..
        - sonar-scanner

    - stage: publish
      script:
        - ./app_deployer.sh generate-tar
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t traffic-analyzer -f docker/Dockerfile-Production .
        - docker images
        - docker tag traffic-analyzer $DOCKER_USERNAME/traffic-analyzer
        - docker push $DOCKER_USERNAME/traffic-analyzer