dist: xenial

notifications:
  email: false

sudo: required

language: python
python:
  - "3.7"

git:
  quiet: true
  depth: false

services:
  - docker

addons:
  sonarcloud:
    organization: "anjo-hsr"
    token:
      secure: $SONAR_TOKEN

before_install:
  - sudo apt-get update
  - sudo apt-get install dos2unix
  - dos2unix ./app_deployer.sh

jobs:
  include:
    - stage: test
      script:
        - cd ./backend
        - mkdir reports
        - nosetests -v --match="^(?:|[\b_\.\-])[Tt]est" --cover-package=bin --cover-min-percentage=60 --cover-inclusive --cover-erase --with-xcoverage --xcoverage-file=./reports/coverage.xml bin/test
        - cd ./bin
        - pylint -r n --rcfile=../.pylintrc main test || pylint-exit $?

    - stage: build
      script:
        - ./app_deployer.sh recreate

    - stage: sonar
      script:
        - cd ./backend
        - mkdir reports
        - nosetests -v --match="^(?:|[\b_\.\-])[Tt]est" --cover-package=bin --cover-min-percentage=60 --cover-inclusive --cover-erase --with-xcoverage --xcoverage-file=./reports/coverage.xml bin/test
        - cd ./bin
        - pylint -r n --rcfile=../.pylintrc main test > ../reports/pylint_report.txt
        - cd ../..
        - sonar-scanner

    - stage: publish docker container
      if: branch = master AND type = push AND fork = false
      script:
        - ./app_deployer.sh generate-tar
        - cd ./docker
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t traffic-analyzer -f ./Dockerfile-Production .
        - docker images
        - docker tag traffic-analyzer $DOCKER_USERNAME/traffic-analyzer
        - docker push $DOCKER_USERNAME/traffic-analyzer