version: "3.7"

services:
  image:
    container_name: "${CONTAINER_NAME}"
    build:
      context: "./${DEPLOYMENT_FOLDER}"
      args:
        WEB_PORT: 8000
        REST_API_PORT: 8089
        INIT_DIR: $INIT_DIR
        SPLUNK_PASSWORD: $SPLUNK_PASSWORD
        SPLUNK_START_ARGS: $SPLUNK_START_ARGS
    restart: $RESTART_NODE
    networks:
      default:
    ports:
      - "${PUBLIC_WEB_PORT}:8000"
      - "${PUBLIC_REST_API_PORT}:8089"